A lot of small improvements, and a fix for #86 and #89
Sefiraat/CrystamaeHistoria pull request #90
Opened 2022-01-26 03:01 UTC by GallowsDove

I've tried to fix the inconsistent use of Nonnull, NotNull and ParametersAreNonnullByDefault.
I've also done some tiny edits where I saw fit.
Furthemore, Item and Block handlers were moved outside of constructors into preRegister function, as is recommended by Slimefun JavaDocs.

At last I've fixed #86 and #89 bugs.

Needs just a bit of testing to make sure I didn't break anything,

2022-01-26 08:14 UTC, Sefiraat requested changes
It's really nice to have someone else's eye on my mess here! Thanks for this. Generally approved but I'll go through some testing when I have time today/tomorrow :)

2022-01-26 08:14 UTC, Sefiraat commented on src/main/java/io/github/sefiraat/crystamaehistoria/slimefun/tools/artistic/PoseCloner.java
>              public void onPlayerPlace(@NotNull BlockPlaceEvent e) {
```suggestion
            public void onPlayerPlace(@Nonnull BlockPlaceEvent e) {
```

2022-01-26 08:14 UTC, Sefiraat commented on src/main/java/io/github/sefiraat/crystamaehistoria/slimefun/tools/covers/BlockVeil.java
> +                                && materialIsValid(offhand.getType())
Continuous Indent to 4

2022-01-26 08:14 UTC, Sefiraat commented on src/main/java/io/github/sefiraat/crystamaehistoria/utils/StoryUtils.java
> +     * @param itemStack The {@link ItemStack} whose meta will have the PDC element added to
Man, I swear I got A* in English in school - I don't deserve to be trusted on peoples servers xD

2022-01-26 18:08 UTC, GallowsDove commented on src/main/java/io/github/sefiraat/crystamaehistoria/magic/spells/core/InstancePlate.java
> -        // Is spell disabled in the spells.yml?
Sure, it just felt like the most obvious part of the code has comments, but almost nothing else does.

2022-01-26 18:19 UTC, Sefiraat reviewed
Looking really good - I'll find some time to test in game then I'll merge :)

2022-01-28 21:07 UTC, Sefiraat approved these changes

2022-01-28 21:16 UTC, merged